version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: haikara_mysql_container
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_container
    volumes:
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./back/uploads:/usr/share/nginx/html/uploads
    ports:
      - "8086:80"
    tty: true

volumes:
  mysql-data:
