// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Feed is the predicate function for feed builders.
type Feed func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// SiteCategory is the predicate function for sitecategory builders.
type SiteCategory func(*sql.Selector)

// SiteCrawlRule is the predicate function for sitecrawlrule builders.
type SiteCrawlRule func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
