// Code generated by ent, DO NOT EDIT.

package ogpimage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/haikara-dev/haikara/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileName), v))
	})
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFilePath), v))
	})
}

// OriginURL applies equality check predicate on the "origin_url" field. It's identical to OriginURLEQ.
func OriginURL(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOriginURL), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFileName), v))
	})
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFileName), v))
	})
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldFileName), v...))
	})
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldFileName), v...))
	})
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFileName), v))
	})
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFileName), v))
	})
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFileName), v))
	})
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFileName), v))
	})
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFileName), v))
	})
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFileName), v))
	})
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFileName), v))
	})
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFileName), v))
	})
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFileName), v))
	})
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFilePath), v))
	})
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFilePath), v))
	})
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldFilePath), v...))
	})
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldFilePath), v...))
	})
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFilePath), v))
	})
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFilePath), v))
	})
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFilePath), v))
	})
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFilePath), v))
	})
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFilePath), v))
	})
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFilePath), v))
	})
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFilePath), v))
	})
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFilePath), v))
	})
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFilePath), v))
	})
}

// OriginURLEQ applies the EQ predicate on the "origin_url" field.
func OriginURLEQ(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOriginURL), v))
	})
}

// OriginURLNEQ applies the NEQ predicate on the "origin_url" field.
func OriginURLNEQ(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOriginURL), v))
	})
}

// OriginURLIn applies the In predicate on the "origin_url" field.
func OriginURLIn(vs ...string) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldOriginURL), v...))
	})
}

// OriginURLNotIn applies the NotIn predicate on the "origin_url" field.
func OriginURLNotIn(vs ...string) predicate.OGPImage {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldOriginURL), v...))
	})
}

// OriginURLGT applies the GT predicate on the "origin_url" field.
func OriginURLGT(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOriginURL), v))
	})
}

// OriginURLGTE applies the GTE predicate on the "origin_url" field.
func OriginURLGTE(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOriginURL), v))
	})
}

// OriginURLLT applies the LT predicate on the "origin_url" field.
func OriginURLLT(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOriginURL), v))
	})
}

// OriginURLLTE applies the LTE predicate on the "origin_url" field.
func OriginURLLTE(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOriginURL), v))
	})
}

// OriginURLContains applies the Contains predicate on the "origin_url" field.
func OriginURLContains(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldOriginURL), v))
	})
}

// OriginURLHasPrefix applies the HasPrefix predicate on the "origin_url" field.
func OriginURLHasPrefix(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldOriginURL), v))
	})
}

// OriginURLHasSuffix applies the HasSuffix predicate on the "origin_url" field.
func OriginURLHasSuffix(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldOriginURL), v))
	})
}

// OriginURLEqualFold applies the EqualFold predicate on the "origin_url" field.
func OriginURLEqualFold(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldOriginURL), v))
	})
}

// OriginURLContainsFold applies the ContainsFold predicate on the "origin_url" field.
func OriginURLContainsFold(v string) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldOriginURL), v))
	})
}

// HasArticle applies the HasEdge predicate on the "article" edge.
func HasArticle() predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ArticleTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ArticleTable, ArticleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArticleWith applies the HasEdge predicate on the "article" edge with a given conditions (other predicates).
func HasArticleWith(preds ...predicate.Article) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ArticleInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ArticleTable, ArticleColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OGPImage) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OGPImage) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OGPImage) predicate.OGPImage {
	return predicate.OGPImage(func(s *sql.Selector) {
		p(s.Not())
	})
}
