// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/haikara-dev/haikara/ent/article"
	"github.com/haikara-dev/haikara/ent/ogpimage"
	"github.com/haikara-dev/haikara/ent/predicate"
)

// OGPImageQuery is the builder for querying OGPImage entities.
type OGPImageQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.OGPImage
	withArticle *ArticleQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OGPImageQuery builder.
func (oiq *OGPImageQuery) Where(ps ...predicate.OGPImage) *OGPImageQuery {
	oiq.predicates = append(oiq.predicates, ps...)
	return oiq
}

// Limit adds a limit step to the query.
func (oiq *OGPImageQuery) Limit(limit int) *OGPImageQuery {
	oiq.limit = &limit
	return oiq
}

// Offset adds an offset step to the query.
func (oiq *OGPImageQuery) Offset(offset int) *OGPImageQuery {
	oiq.offset = &offset
	return oiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oiq *OGPImageQuery) Unique(unique bool) *OGPImageQuery {
	oiq.unique = &unique
	return oiq
}

// Order adds an order step to the query.
func (oiq *OGPImageQuery) Order(o ...OrderFunc) *OGPImageQuery {
	oiq.order = append(oiq.order, o...)
	return oiq
}

// QueryArticle chains the current query on the "article" edge.
func (oiq *OGPImageQuery) QueryArticle() *ArticleQuery {
	query := &ArticleQuery{config: oiq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ogpimage.Table, ogpimage.FieldID, selector),
			sqlgraph.To(article.Table, article.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ogpimage.ArticleTable, ogpimage.ArticleColumn),
		)
		fromU = sqlgraph.SetNeighbors(oiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OGPImage entity from the query.
// Returns a *NotFoundError when no OGPImage was found.
func (oiq *OGPImageQuery) First(ctx context.Context) (*OGPImage, error) {
	nodes, err := oiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ogpimage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oiq *OGPImageQuery) FirstX(ctx context.Context) *OGPImage {
	node, err := oiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OGPImage ID from the query.
// Returns a *NotFoundError when no OGPImage ID was found.
func (oiq *OGPImageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ogpimage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oiq *OGPImageQuery) FirstIDX(ctx context.Context) int {
	id, err := oiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OGPImage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OGPImage entity is found.
// Returns a *NotFoundError when no OGPImage entities are found.
func (oiq *OGPImageQuery) Only(ctx context.Context) (*OGPImage, error) {
	nodes, err := oiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ogpimage.Label}
	default:
		return nil, &NotSingularError{ogpimage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oiq *OGPImageQuery) OnlyX(ctx context.Context) *OGPImage {
	node, err := oiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OGPImage ID in the query.
// Returns a *NotSingularError when more than one OGPImage ID is found.
// Returns a *NotFoundError when no entities are found.
func (oiq *OGPImageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ogpimage.Label}
	default:
		err = &NotSingularError{ogpimage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oiq *OGPImageQuery) OnlyIDX(ctx context.Context) int {
	id, err := oiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OGPImages.
func (oiq *OGPImageQuery) All(ctx context.Context) ([]*OGPImage, error) {
	if err := oiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return oiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (oiq *OGPImageQuery) AllX(ctx context.Context) []*OGPImage {
	nodes, err := oiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OGPImage IDs.
func (oiq *OGPImageQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := oiq.Select(ogpimage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oiq *OGPImageQuery) IDsX(ctx context.Context) []int {
	ids, err := oiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oiq *OGPImageQuery) Count(ctx context.Context) (int, error) {
	if err := oiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return oiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (oiq *OGPImageQuery) CountX(ctx context.Context) int {
	count, err := oiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oiq *OGPImageQuery) Exist(ctx context.Context) (bool, error) {
	if err := oiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return oiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (oiq *OGPImageQuery) ExistX(ctx context.Context) bool {
	exist, err := oiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OGPImageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oiq *OGPImageQuery) Clone() *OGPImageQuery {
	if oiq == nil {
		return nil
	}
	return &OGPImageQuery{
		config:      oiq.config,
		limit:       oiq.limit,
		offset:      oiq.offset,
		order:       append([]OrderFunc{}, oiq.order...),
		predicates:  append([]predicate.OGPImage{}, oiq.predicates...),
		withArticle: oiq.withArticle.Clone(),
		// clone intermediate query.
		sql:    oiq.sql.Clone(),
		path:   oiq.path,
		unique: oiq.unique,
	}
}

// WithArticle tells the query-builder to eager-load the nodes that are connected to
// the "article" edge. The optional arguments are used to configure the query builder of the edge.
func (oiq *OGPImageQuery) WithArticle(opts ...func(*ArticleQuery)) *OGPImageQuery {
	query := &ArticleQuery{config: oiq.config}
	for _, opt := range opts {
		opt(query)
	}
	oiq.withArticle = query
	return oiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OGPImage.Query().
//		GroupBy(ogpimage.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oiq *OGPImageQuery) GroupBy(field string, fields ...string) *OGPImageGroupBy {
	grbuild := &OGPImageGroupBy{config: oiq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := oiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return oiq.sqlQuery(ctx), nil
	}
	grbuild.label = ogpimage.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OGPImage.Query().
//		Select(ogpimage.FieldCreatedAt).
//		Scan(ctx, &v)
func (oiq *OGPImageQuery) Select(fields ...string) *OGPImageSelect {
	oiq.fields = append(oiq.fields, fields...)
	selbuild := &OGPImageSelect{OGPImageQuery: oiq}
	selbuild.label = ogpimage.Label
	selbuild.flds, selbuild.scan = &oiq.fields, selbuild.Scan
	return selbuild
}

func (oiq *OGPImageQuery) prepareQuery(ctx context.Context) error {
	for _, f := range oiq.fields {
		if !ogpimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oiq.path != nil {
		prev, err := oiq.path(ctx)
		if err != nil {
			return err
		}
		oiq.sql = prev
	}
	return nil
}

func (oiq *OGPImageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OGPImage, error) {
	var (
		nodes       = []*OGPImage{}
		withFKs     = oiq.withFKs
		_spec       = oiq.querySpec()
		loadedTypes = [1]bool{
			oiq.withArticle != nil,
		}
	)
	if oiq.withArticle != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, ogpimage.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*OGPImage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &OGPImage{config: oiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oiq.withArticle; query != nil {
		if err := oiq.loadArticle(ctx, query, nodes, nil,
			func(n *OGPImage, e *Article) { n.Edges.Article = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oiq *OGPImageQuery) loadArticle(ctx context.Context, query *ArticleQuery, nodes []*OGPImage, init func(*OGPImage), assign func(*OGPImage, *Article)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OGPImage)
	for i := range nodes {
		if nodes[i].article_ogp_image == nil {
			continue
		}
		fk := *nodes[i].article_ogp_image
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(article.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "article_ogp_image" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (oiq *OGPImageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oiq.querySpec()
	_spec.Node.Columns = oiq.fields
	if len(oiq.fields) > 0 {
		_spec.Unique = oiq.unique != nil && *oiq.unique
	}
	return sqlgraph.CountNodes(ctx, oiq.driver, _spec)
}

func (oiq *OGPImageQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := oiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (oiq *OGPImageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ogpimage.Table,
			Columns: ogpimage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ogpimage.FieldID,
			},
		},
		From:   oiq.sql,
		Unique: true,
	}
	if unique := oiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := oiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ogpimage.FieldID)
		for i := range fields {
			if fields[i] != ogpimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oiq *OGPImageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oiq.driver.Dialect())
	t1 := builder.Table(ogpimage.Table)
	columns := oiq.fields
	if len(columns) == 0 {
		columns = ogpimage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oiq.sql != nil {
		selector = oiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oiq.unique != nil && *oiq.unique {
		selector.Distinct()
	}
	for _, p := range oiq.predicates {
		p(selector)
	}
	for _, p := range oiq.order {
		p(selector)
	}
	if offset := oiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OGPImageGroupBy is the group-by builder for OGPImage entities.
type OGPImageGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oigb *OGPImageGroupBy) Aggregate(fns ...AggregateFunc) *OGPImageGroupBy {
	oigb.fns = append(oigb.fns, fns...)
	return oigb
}

// Scan applies the group-by query and scans the result into the given value.
func (oigb *OGPImageGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := oigb.path(ctx)
	if err != nil {
		return err
	}
	oigb.sql = query
	return oigb.sqlScan(ctx, v)
}

func (oigb *OGPImageGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range oigb.fields {
		if !ogpimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := oigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (oigb *OGPImageGroupBy) sqlQuery() *sql.Selector {
	selector := oigb.sql.Select()
	aggregation := make([]string, 0, len(oigb.fns))
	for _, fn := range oigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(oigb.fields)+len(oigb.fns))
		for _, f := range oigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(oigb.fields...)...)
}

// OGPImageSelect is the builder for selecting fields of OGPImage entities.
type OGPImageSelect struct {
	*OGPImageQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ois *OGPImageSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ois.prepareQuery(ctx); err != nil {
		return err
	}
	ois.sql = ois.OGPImageQuery.sqlQuery(ctx)
	return ois.sqlScan(ctx, v)
}

func (ois *OGPImageSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ois.sql.Query()
	if err := ois.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
